- name: Update apt repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Apache, PHP en PHP-MySQL
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Start en enable Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
